name: setup-home
description: Small useful action for when you need to sign commits in CI, or need to access or push to private repos.
author: Bart Oostveen
inputs:
  ssh-private-key:
    description: SSH private key to use, gets stored in $HOME/.ssh/id_ed25519
    required: false
  ssh-known-hosts:
    description: SSH known hosts file, useful for locking the Git forge's public keys
    required: false
  gpg-privkey:
    description: GPG private key to import in the OpenPGP keyboy
    required: false
  gpg-key-id:
    description: GPG key ID of the PGP key in `gpg-privkey`
    required: false
  forge-hostname:
    description: Hostname of the Git forge this action runs on, gets populated in the SSH config
    required: true
    default: git.bartoostveen.nl
  forge-username:
    description: Username of the Git forge this action runs on
    required: true
    default: forgejo
  git-user-name:
    description: Git committer username, gets used when running `git commit`
    required: true
    default: "forgejo-actions[bot]"
  git-user-email:
    description: Git committer email, gets used when running `git commit`
    required: true
    default: "git@bartoostveen.nl"
  verbose:
    description: Whether to be verbose (log debug SSH config / connection tests)
    required: true
    default: "false"
runs:
  using: composite
  steps:
    - name: Create home directory
      shell: bash
      run: |
        export HOME="$RUNNER_TEMP"
        echo "Setting up home directory in $HOME"
        mkdir -p "$HOME/.ssh"
        chmod -R 700 "$HOME/.ssh"
        echo "HOME=$HOME" >> "$FORGEJO_ENV"
    - name: Setup SSH
      shell: bash
      if: inputs.ssh-private-key && inputs.ssh-known-hosts
      run: |
        printf '%s\n' "$SSH_PRIVATE_KEY" > "$HOME/.ssh/id_ed25519"
        chmod 600 "$HOME/.ssh/id_ed25519"
        printf '%s\n' "$SSH_KNOWN_HOSTS" > "$HOME/.ssh/known_hosts"
        chmod 644 "$HOME/.ssh/known_hosts"

        cat > "$HOME/.ssh/config" <<EOF
        Host $FORGE_HOSTNAME
          IdentityFile "$HOME/.ssh/id_ed25519"
          User $FORGE_USERNAME
          StrictHostKeyChecking yes
          UserKnownHostsFile "$HOME/.ssh/known_hosts"
        EOF

        chmod 600 "$HOME/.ssh/config"

        SSH_FLAGS=""
        if [[ "$VERBOSE" == "true" ]]; then
          SSH_FLAGS="-vv $SSH_FLAGS"

          echo "--- START SSH CONFIG ---"
          cat "$HOME/.ssh/config"
          echo "--- END SSH CONFIG ---"
          echo "Trying to connect..."
        fi
        ssh "$SSH_FLAGS" -T -F "$HOME/.ssh/config" $FORGE_USERNAME@$FORGE_HOSTNAME

        export GIT_SSH_COMMAND="ssh -F "$HOME/.ssh/config""
        echo "GIT_SSH_COMMAND=$GIT_SSH_COMMAND" >> "$FORGEJO_ENV"
      env:
        SSH_PRIVATE_KEY: "${{ inputs.ssh-private-key }}"
        SSH_KNOWN_HOSTS: "${{ inputs.ssh-known-hosts }}"
        FORGE_HOSTNAME: "${{ inputs.forge-hostname }}"
        FORGE_USERNAME: "${{ inputs.forge-username }}"
        VERBOSE: "${{ inputs.verbose }}"
    - name: import GPG key
      shell: bash
      if: inputs.gpg-privkey && inputs.gpg-key-id
      run: |
        gpg --import <(cat <<< "${GPG_PRIVKEY:?}")
        git config --global user.signingKey "${GPG_KEY_ID:?}"
        git config --global commit.gpgSign true
      env:
        GPG_PRIVKEY: "${{ inputs.gpg-privkey }}"
        GPG_KEY_ID: "${{ inputs.gpg-key-id }}"
    - name: configure git
      shell: bash
      run: |
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_USER_EMAIL"
        git config --global push.default simple
      env:
        GIT_USER_NAME: "${{ inputs.git-user-name }}"
        GIT_USER_EMAIL: "${{ inputs.git-user-email }}"
    - name: check
      if: inputs.ssh-private-key && inputs.ssh-known-hosts
      shell: bash
      run: |
        git ls-remote \
          ssh://$FORGE_USERNAME@$FORGE_HOSTNAME/$FORGEJO_REPOSITORY.git
      env:
        FORGE_HOSTNAME: "${{ inputs.forge-hostname }}"
        FORGE_USERNAME: "${{ inputs.forge-username }}"
