name: Docker integration test
"on":
  push:
  pull_request:
jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      # TODO: remove (https://github.com/podman-container-tools/podman/issues/29805)
      - name: Fix /var/run symlink for Podman
        run: |
          rm -f /var/run
          mkdir -p /var/run
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ./
        with:
          gpg-privkey: ${{ secrets.GPG_PRIVKEY }}
          gpg-key-id: ${{ vars.GPG_KEY_ID }}
          nix-github-token: ${{ secrets.NIX_GITHUB_TOKEN }}
